# Main Nexus Configuration
# This file is discoverable in the project root and contains core settings

project:
  name: "Nexus"
  version: "1.0.0"
  description: "A modular project framework for AI-assisted development"

environment: "development"

directories:
  docs: "generated-docs"
  cache: ".nexus/cache"
  logs: ".nexus/logs"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "nexus.log"
  max_size: 10485760  # 10MB
  backup_count: 5

documentation:
  formats: ["html", "markdown"]
  auto_generate: true

execution:
  max_parallel: 4
  timeout: 300
  retry_attempts: 3

server:
  host: "localhost"
  port: 8000

features:
  auto_reload: true
  debug_mode: false
  experimental_features: false
